import Link from "next/link";

const plans=[
["FORTUNE FREE","$0","Start learning and practicing","Demo Trade Lab","Academy lessons","Basic AI Coach"],
["FORTUNE PRO","$29","For serious practice","Advanced demo analytics","Full Academy","AI Coach tools","Strategy Center"],
["FORTUNE ELITE","$79","For advanced traders","Everything in Pro","Premium research workspace","Advanced risk tools"]
];

export default function Pricing(){return <main className="page"><header className="nav"><Link className="brand" href="/">TF<span>AI</span></Link><nav><Link href="/">Markets</Link><Link href="/education">Academy</Link><Link href="/coach">AI Coach</Link><Link href="/trade-lab">Trade Lab</Link><Link href="/pricing">Pricing</Link></nav></header><div className="wrap"><div className="eyebrow">TRADERS FORTUNE AI</div><h1>CHOOSE YOUR LEVEL.</h1><p className="sub">Subscription-ready pricing structure. Billing can be connected when your payment provider is configured.</p><div className="grid">{plans.map((p,i)=><article className={i===1?"featured":""} key={p[0]}><div className="tag">{i===1?"MOST POPULAR":"PLAN"}</div><h2>{p[0]}</h2><strong>{p[1]}<small>/mo</small></strong><p>{p[2]}</p><ul>{p.slice(3).map(x=><li key={x}>✓ {x}</li>)}</ul><button onClick={()=>alert("Demo checkout placeholder. Connect your payment provider to enable billing.")}>CHOOSE PLAN</button></article>)}</div></div><style jsx>{`.page{min-height:100vh;background:#050608;color:#fff}.nav{height:72px;border-bottom:1px solid #20242b;display:flex;align-items:center;padding:0 5%;gap:30px}.brand{font-size:25px;font-weight:900}.brand span{color:#b886ff}.nav nav{display:flex;gap:22px;flex:1;color:#9da4af;font-size:13px}.wrap{padding:70px 7%}.eyebrow{color:#b7ff3c;font-size:10px;letter-spacing:2px;font-weight:900}h1{font-size:60px;margin:12px 0;letter-spacing:-3px}.sub{color:#8e97a4;max-width:650px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:45px}article{background:#0c0f14;border:1px solid #252b34;border-radius:14px;padding:28px;min-height:410px}.featured{border-color:#b7ff3c}.tag{font-size:9px;color:#b7ff3c;letter-spacing:1px}h2{margin-top:25px;font-size:20px}strong{font-size:43px;display:block;margin:20px 0}small{font-size:12px;color:#7d8794}article p,li{color:#929ba7;font-size:13px;line-height:1.6}ul{list-style:none;padding:0;min-height:100px}button{width:100%;padding:13px;background:#b7ff3c;border:0;border-radius:7px;font-weight:900}@media(max-width:800px){.nav{padding:0 18px}.nav nav{display:none}.wrap{padding:50px 18px}h1{font-size:45px}.grid{grid-template-columns:1fr}}`}</style></main>}
